services:
  postgres:
    image: postgres:17-alpine3.21
    container_name: postgres
    environment:
      POSTGRES_DB: books
      POSTGRES_USER: yu71
      POSTGRES_PASSWORD: 53ccret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
